typography_spectrum: 0.660241051344201
color:
  brandColors:
    - '#000000'
    - '#bec1b6'
    - '#fefefe'
    - '#8c8678'
    - '#685c4f'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: billfelty
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2c0defc2-315b-4072-b89f-f3ee227d0a20.jpg
title: null
purpose: []
