name: billfelty
favicon: null
layout_spectrum: 0.2296709823422134
typography_spectrum: 0.660241051344201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49330343678593636
  lightness: 0.28041668701916933
  saturation: 0.08348183683119714
  rhythmicContrast: 0.5234916766639799
purpose: []
