name: billfelty
favicon: null
layout_spectrum: 0.2296709823422134
typography_spectrum: 0.660241051344201
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9ec0eb'
    - '#242328'
    - '#ac7262'
    - '#f9f2e0'
    - '#cadb5b'
  brandStrength: 0.49330343678593636
  lightness: 0.28041668701916933
  saturation: 0.08348183683119714
  rhythmicContrast: 0.5234916766639799
purpose: []
