name: billfelty
favicon: null
layout_spectrum: 0.73193
typography_spectrum: 0.660241051344201
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bec1b6'
    - '#fefefe'
    - '#8c8678'
    - '#685c4f'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose: []
